### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by hygxy** [thodan/obj_pose_eval#2]
Hey, thanks for creating this tool, could you please also add python3 support?

**Comment by thodan** [comment]
Hi, please use the BOP Toolkit (https://github.com/thodan/bop_toolkit) instead of obj_pose_eval. Most of its functionality (including the functions to evaluate 6D object pose) supports python 3.

**Comment by wangg12** [comment]
@thodan Some code of the bop toolkit does not support python3, for example `np.mean(some_dict.values()), map`. Anyway, they could be easily fixed.
