### ISSUE TITLE
Nvidia Deep Pose - Testing

### ISSUE THREAD

**Issue by IbrahimMCode** [thodan/obj_pose_eval#5]
Hello, 
Is it possible to test the Nvidia deep pose models same as the eval_rotating_cup?

Thank you!

**Comment by thodan** [comment]
Hello, to evaluate 6D object pose estimation methods (such as Nvidia deep pose), please use the [BOP Toolkit](https://github.com/thodan/bop_toolkit) or the [BOP online evaluation system](https://bop.felk.cvut.cz/home/). The eval_rotating_cup (and the associated ECCVW'16 paper) was one of the first steps leading to the BOP benchmark.

**Comment by Abduoit** [comment]
Hi, 
I am trying to evaluate `Dope` obj pose estimation. Like calculating ADD metrics, but I can't find any example or implementation steps? any help will be appreciated

**Comment by thodan** [comment]
Hello, the obj_pose_eval repository is no longer maintained. Instead, please use the [BOP Toolkit](https://github.com/thodan/bop_toolkit) which includes all of the functionality. Please refer to [this issue](https://github.com/thodan/bop_toolkit/issues/37) to see how to use ADD/ADI for the evaluation using the BOP Toolkit.
